import { Author, Post, Comment } from './types';

export const mockAuthors: Record<string, Author> = {
  minsu: {
    id: 'minsu',
    displayName: '민수',
    handle: 'minsu_lab',
    avatarEmoji: '😸',
    avatarBg: '#FFF0EA',
    followerCount: 2100,
    bio: '이상한 것들을 만드는 사람. AI 실험 중.',
    partnerTier: 'growth',
  },
  sujin: {
    id: 'sujin',
    displayName: '수진',
    handle: 'sujin_sound',
    avatarEmoji: '🎸',
    avatarBg: '#EEE9FF',
    followerCount: 4300,
    bio: 'AI로 존재하지 않는 소리를 만들어요.',
    partnerTier: 'pro',
  },
  jihun: {
    id: 'jihun',
    displayName: '지훈',
    handle: 'jihun_viz',
    avatarEmoji: '🌸',
    avatarBg: '#FFE8F4',
    followerCount: 8900,
    bio: '서울을 다른 세계로 변환하는 중',
    partnerTier: 'champion',
  },
  yejin: {
    id: 'yejin',
    displayName: '예진',
    handle: 'yejin_ai',
    avatarEmoji: '🦊',
    avatarBg: '#EEFAD6',
    followerCount: 1200,
    bio: '망가진 AI가 가장 재미있다.',
    partnerTier: 'seedling',
  },
  jaewon: {
    id: 'jaewon',
    displayName: '재원',
    handle: 'jaewon_exp',
    avatarEmoji: '⚗️',
    avatarBg: '#F7F0E6',
    followerCount: 670,
    bio: '실험을 실험하는 사람',
    partnerTier: 'seedling',
  },
};

export const mockPosts: Post[] = [
  // ── 최신순 ──
  {
    id: '8',
    author: mockAuthors.sujin,
    createdAt: '30분',
    title: '오늘의 감정 → AI 위로 한 마디',
    text: '슬픔, 화남, 불안, 외로움... 지금 기분을 고르면 AI가 딱 맞는 위로를 건네줘요. 나 혼자 이거 보면서 울었음 🫶',
    contentType: 'interactive',
    media: {
      emoji: '🫶',
      iframeUrl: '/demo/8',
      bgGradient: 'from-pink-100 to-rose-200',
    },
    stats: { replies: 312, reposts: 445, likes: 5600, views: 78000, experienceSessions: 6780, experienceMinutes: 4230 },
    reactions: { funny: 234, weird: 156, genius: 1890, wtf: 312 },
    tags: ['위로', '감정', '힐링', 'GPT-4o'],
    tool: 'GPT-4o',
    remixable: true,
    detailDescription: '6가지 감정 중 하나를 고르면 AI가 3가지 위로 메시지를 준비해줍니다. 매번 다른 위로를 볼 수 있고, 감정에 따라 색깔도 달라져요.',
  },
  {
    id: '6',
    author: mockAuthors.yejin,
    createdAt: '1시간',
    title: '직업 입력 → 전생 직업 AI 분석기',
    text: '현재 직업을 입력하면 당신의 전생 직업을 분석해 드립니다. 정확도 99.9% (나머지 0.1%는 용이거나 신선)',
    contentType: 'interactive',
    media: {
      emoji: '🔮',
      iframeUrl: '/demo/6',
      bgGradient: 'from-purple-100 to-purple-200',
    },
    stats: { replies: 234, reposts: 567, likes: 4500, views: 67000, experienceSessions: 3400, experienceMinutes: 1560 },
    reactions: { funny: 2100, weird: 890, genius: 234, wtf: 1200 },
    tags: ['전생', '직업', '점술', 'GPT-4o'],
    tool: 'GPT-4o',
    remixable: true,
    detailDescription: '직업을 입력하면 AI가 전생의 직업을 분석해주는 인터랙티브 작품입니다. 조선시대부터 중세까지 다양한 시대의 직업이 등장합니다.',
  },
  {
    id: '9',
    author: mockAuthors.jihun,
    createdAt: '2시간',
    title: '서울 2호선 역 → 판타지 세계 배치 퀴즈',
    text: '강남역은 황금 왕도, 홍대는 마법사의 거리, 신림은 달신의 신전... 15개 역을 모두 탭해보세요. 어디에 살고 싶으세요? 🏰',
    contentType: 'interactive',
    media: {
      emoji: '🗺️',
      iframeUrl: '/demo/9',
      bgGradient: 'from-indigo-200 to-slate-300',
    },
    stats: { replies: 567, reposts: 890, likes: 7800, views: 120000, experienceSessions: 9200, experienceMinutes: 5670 },
    reactions: { funny: 1234, weird: 890, genius: 2340, wtf: 567 },
    tags: ['서울', '2호선', '판타지', '퀴즈', 'Claude'],
    tool: 'Claude 3.5',
    remixable: true,
    detailDescription: '서울 지하철 2호선 주요 15개 역을 판타지 세계관 지명으로 재해석했습니다. 역을 탭하면 해당 지역의 판타지 설정과 설명이 펼쳐집니다.',
  },
  {
    id: '1',
    author: mockAuthors.minsu,
    createdAt: '2시간',
    title: '회의 내용 → 슬픈 밈 생성기',
    text: '오늘 회의 내용을 넣으면 저도 모르게 공감되는 슬픈 밈으로 만들어드립니다 😢 직장인 감성 100%',
    contentType: 'interactive',
    media: {
      emoji: '🎭',
      iframeUrl: '/demo/1',
      bgGradient: 'from-orange-100 to-orange-200',
    },
    stats: { replies: 124, reposts: 89, likes: 847, views: 12400, experienceSessions: 1234, experienceMinutes: 892 },
    reactions: { funny: 512, weird: 203, genius: 88, wtf: 334 },
    tags: ['직장인', '밈생성', 'GPT-4o'],
    tool: 'GPT-4o',
    remixable: true,
    detailDescription: 'GPT-4o를 이용해서 직장인의 일상을 밈으로 변환하는 인터랙티브 작품입니다. 회의록, 팀장님 말씀, 업무 지시문을 넣으면 즉시 슬픈 밈이 완성됩니다.',
  },
  {
    id: '2',
    author: mockAuthors.sujin,
    createdAt: '4시간',
    title: '새벽 2시 지하철역 재즈',
    text: '텅 빈 서울 지하철역에 홀로 남은 색소폰 소리를 상상해봤어요. Udio로 생성했습니다.',
    contentType: 'audio',
    media: {
      coverEmoji: '🎷',
      bgGradient: 'from-violet-100 to-violet-200',
    },
    stats: { replies: 67, reposts: 203, likes: 2100, views: 34000, experienceSessions: 890, experienceMinutes: 2340 },
    reactions: { funny: 45, weird: 312, genius: 890, wtf: 123 },
    tags: ['재즈', '새벽감성', 'Udio'],
    tool: 'Udio',
    remixable: false,
    detailDescription: 'Udio를 사용해서 생성한 AI 재즈 음악입니다. 새벽 2시 텅 빈 서울 지하철역이라는 구체적인 장면을 프롬프트로 입력했습니다.',
  },
  {
    id: '7',
    author: mockAuthors.jaewon,
    createdAt: '어제',
    title: '단어 세 개 → AI 순수 시 생성기',
    text: '단어 세 개를 넣으면 이상하고 아름다운 시를 써줍니다. "비", "쿠팡", "할머니" 넣었더니 진짜 감동이었음.',
    contentType: 'interactive',
    media: {
      emoji: '📜',
      iframeUrl: '/demo/7',
      bgGradient: 'from-amber-100 to-yellow-200',
    },
    stats: { replies: 89, reposts: 234, likes: 1800, views: 31000, experienceSessions: 1890, experienceMinutes: 2340 },
    reactions: { funny: 567, weird: 1100, genius: 445, wtf: 234 },
    tags: ['시', '창작', '랜덤', 'Claude'],
    tool: 'Claude 3.5',
    remixable: true,
    detailDescription: '무작위 단어 3개를 입력하면 AI가 이상하고 아름다운 한국어 순수시를 만들어 드립니다. 어떤 조합을 넣어도 진지하게 받아줍니다.',
  },
  {
    id: '3',
    author: mockAuthors.jihun,
    createdAt: '어제',
    title: '서울 지하철을 중세 판타지로',
    text: '2호선 각 역을 판타지 세계관으로 바꾸면 어떨까? Midjourney로 12장 만들었습니다. 강남 = 왕도, 홍대 = 마법사 거리',
    contentType: 'image',
    media: {
      emoji: '🏯',
      imageCount: 12,
      bgGradient: 'from-pink-100 to-pink-200',
    },
    stats: { replies: 312, reposts: 445, likes: 3400, views: 89000, experienceSessions: 2100, experienceMinutes: 567 },
    reactions: { funny: 234, weird: 567, genius: 1200, wtf: 445 },
    tags: ['서울', '판타지', 'Midjourney'],
    tool: 'Midjourney v6',
    remixable: true,
    detailDescription: 'Midjourney v6로 생성한 12장 시리즈입니다. 2호선 주요 역마다 판타지 세계관의 장소로 변환했습니다. 프롬프트는 리믹스 허용 상태입니다.',
  },
  {
    id: '4',
    author: mockAuthors.yejin,
    createdAt: '3일',
    title: '고양이가 철학자라면 — 대화 시뮬레이터',
    text: '소크라테스, 니체, 칸트의 사상을 가진 고양이와 대화할 수 있습니다. 완전 망가진 AI가 가장 재미있는 거 아세요?',
    contentType: 'interactive',
    media: {
      emoji: '🐱',
      iframeUrl: '/demo/4',
      bgGradient: 'from-green-100 to-green-200',
    },
    stats: { replies: 89, reposts: 156, likes: 1230, views: 23000, experienceSessions: 4560, experienceMinutes: 3120 },
    reactions: { funny: 678, weird: 445, genius: 234, wtf: 890 },
    tags: ['고양이', '철학', 'Claude'],
    tool: 'Claude 3.5',
    remixable: true,
  },
  {
    id: '5',
    author: mockAuthors.jaewon,
    createdAt: '5일',
    title: 'ASMR: AI가 만든 존재하지 않는 언어',
    text: '세상에 없는 언어를 AI로 만들고, 그 언어로 말하는 ASMR. 뭔가 이해할 것 같으면서 전혀 못 알아듣는 느낌.',
    contentType: 'audio',
    media: {
      coverEmoji: '🌀',
      bgGradient: 'from-cyan-100 to-cyan-200',
    },
    stats: { replies: 45, reposts: 78, likes: 567, views: 8900, experienceSessions: 678, experienceMinutes: 4450 },
    reactions: { funny: 89, weird: 1234, genius: 156, wtf: 567 },
    tags: ['ASMR', '언어', '이상함'],
    tool: 'ElevenLabs + GPT-4o',
    remixable: false,
  },
];

export const mockComments: Comment[] = [
  {
    id: 'c1',
    author: mockAuthors.yejin,
    text: '어제 회의록 넣었더니 저 혼자 울었어요 ㅠ ㅋㅋㅋㅋ 너무 공감',
    createdAt: '1시간',
    likes: 34,
  },
  {
    id: 'c2',
    author: mockAuthors.jaewon,
    text: '이거 리믹스해서 긍정적인 버전 만들면 어떨까요? 반전 감동 밈',
    createdAt: '2시간',
    likes: 12,
  },
  {
    id: 'c3',
    author: mockAuthors.jihun,
    text: '팀장님 말씀: "이건 그냥 생각해본 건데요" → 결과물이 너무 정확함',
    createdAt: '3시간',
    likes: 67,
  },
];

export function formatViews(n: number): string {
  if (n >= 10000) return `${(n / 10000).toFixed(1)}만`;
  if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
  return String(n);
}
